source-file ~/.config/tmux/tmux.bindings.conf

set -g prefix ^A
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 100000
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top

set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'catppuccin/tmux'


set -g @resurrect-strategy-nvim 'session'
set -g @catppuccin_flavour 'macchiato'

run '~/.config/tmux/plugins/tpm/tpm'
