import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--command", '"zellij"']

[window]
opacity = 0.95
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[font]
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 13

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Block"}
