"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Renatillas"
email = "renata.amutio@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
pager = ["delta", "--features=decorations side-by-side"]
diff-formatter = ":git"

[aliases]
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
